version: '3'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data: {}