version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: database_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongodb_data: {}